### ISSUE TITLE
Allow CSV (that was edited) to be downloaded as XLS or CSV or both

### ISSUE THREAD

**Issue by ksingh-scogo** [gristlabs/grist-static#33]
Hey Guys, thanks for developing and open-sourcing grist-static , this is an amazing tool to view CSVs on the flow
I have gone through the documentation and you have clearly positioned Grist-Static as CSV Viewer

However I am wondering , if grist-static can also allow in-browser edited CSVs for download, this would be fantastic

### User Flow
- Select or browser a CSV into grist static 
-  View the CSV
-  Add/Delete/Edit  : Row/Column/Cell
- Click on Download CSV or XLS 

### Product Screenshots
- Currently GS allows user to delete/edit CSV in-browser
<img width="1300" alt="image" src="https://github.com/gristlabs/grist-static/assets/76433381/736bed13-2cd1-4c31-b980-50bf841d5c87">

- There is also a button to download the updated CSV
<img width="1683" alt="image" src="https://github.com/gristlabs/grist-static/assets/76433381/810f6854-db10-4f91-b12e-ed01e2649d1c">

- However the download does not work, because A) it tries to downloads the file as HTML  B) Even the HTML does not gets download

<img width="1339" alt="image" src="https://github.com/gristlabs/grist-static/assets/76433381/c6367be9-12fc-48b1-9637-0a659157e6dd">

- Browser failed download history of grist-static downloaded files

<img width="772" alt="image" src="https://github.com/gristlabs/grist-static/assets/76433381/e8fcf0e1-9754-4c09-a190-d499dc1c8385">

**Comment by paulfitz** [comment]
Hi @ksingh-scogo, thanks for reporting - this is definitely on our list of things to do, and you taking the time to report it bumps the odds of it happening sooner rather than later.

Some background: `grist-static` is a light repackaging of our main [`grist-core`](https://github.com/gristlabs/grist-core/) app. In `grist-core`, most Grist document operations are implemented over a websocket to a node app, which has been rerouted in `grist-static`, achieving support of all those operations in one fell swoop. A few operations work differently, and the plumbing for them hasn't been set up yet. Imports and exports fall into this category. Definitely makes sense to continue our work to include them.

**Comment by ksingh-scogo** [comment]
Thanks @paulfitz  for your quick turnaround and positive response.

I will be keeping a close eye on this thread and happy to test that and share feedback , once its there.

**Comment by paulfitz** [comment]
@ksingh-scogo work has started https://github.com/gristlabs/grist-core/pull/665 and I do have a proof of concept in hand.

**Comment by paulfitz** [comment]
This should now be resolved.

**Comment by ksingh-scogo** [comment]
Thanks @paulfitz this works great.
